# Generated by Django 5.0.4 on 2024-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.IntegerField(help_text='ID администратора', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(help_text='Электронная почта администратора', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(help_text='Пароль администратора', max_length=500),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ansid',
            field=models.TextField(help_text='ID ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='qid',
            field=models.TextField(help_text='ID вопроса'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(help_text='Дата отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Электронная почта отправителя отзыва', max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(help_text='Содержание отзыва', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.TextField(help_text='Уникальный идентификатор отзыва', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Имя отправителя отзыва', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(help_text='Тема отзыва', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='time',
            field=models.CharField(help_text='Время отзыва', max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Дата сохранения записи'),
        ),
        migrations.AlterField(
            model_name='history',
            name='eid',
            field=models.TextField(help_text='ID мероприятия'),
        ),
        migrations.AlterField(
            model_name='history',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254),
        ),
        migrations.AlterField(
            model_name='history',
            name='level',
            field=models.IntegerField(help_text='Уровень'),
        ),
        migrations.AlterField(
            model_name='history',
            name='sahi',
            field=models.IntegerField(help_text='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='history',
            name='score',
            field=models.IntegerField(help_text='Баллы'),
        ),
        migrations.AlterField(
            model_name='history',
            name='wrong',
            field=models.IntegerField(help_text='Неправильные ответы'),
        ),
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(help_text='Вариант ответа', max_length=5000),
        ),
        migrations.AlterField(
            model_name='options',
            name='optionid',
            field=models.TextField(help_text='ID варианта ответа'),
        ),
        migrations.AlterField(
            model_name='options',
            name='qid',
            field=models.CharField(help_text='ID вопроса', max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice',
            field=models.IntegerField(help_text='Выбор'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='eid',
            field=models.TextField(help_text='ID мероприятия'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qid',
            field=models.TextField(help_text='ID вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qns',
            field=models.TextField(help_text='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sn',
            field=models.IntegerField(help_text='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct',
            field=models.IntegerField(help_text='Количество правильных ответов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Дата сохранения записи'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='eid',
            field=models.TextField(help_text='ID мероприятия'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='intro',
            field=models.TextField(help_text='Вступление'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tag',
            field=models.CharField(help_text='Тег', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time',
            field=models.BigIntegerField(help_text='Время'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(help_text='Заголовок викторины', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total',
            field=models.IntegerField(help_text='Общее количество вопросов'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='wrong',
            field=models.IntegerField(help_text='Количество неправильных ответов'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254),
        ),
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.IntegerField(help_text='Баллы'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='Дата сохранения записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Электронная почта пользователя', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Имя пользователя', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль пользователя', max_length=50),
        ),
    ]
