# Generated by Django 5.0.4 on 2024-04-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_admin_admin_id_alter_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная', 'verbose_name_plural': 'Обратная'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
